//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.27 at 11:03:34 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mediawiki.org/xml/export-0.10/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mediawiki.xml.export_0;
